#!/bin/bash


# This modificaiton adds support for an external transfer switch ahead of the
# MultiPlus inverter/charger AC input so that both grid and generator may be used
# Quattros provide a second AC input and internal switching between them
# A Multi only has one AC input so grid/generator switching must occur
# up stream of the Multi's AC input
#

packageLogFile="/var/log/ExtTransferSwitch/current"

#### TODO: add update SetupHelper call and exit if it's being updated
#### TODO: add new exit code for setup helper too old
#		this won't help with initial installs but it'll be there for future updates


#### following lines incorporate SetupHelper utilities into this script
# Refer to the SetupHelper ReadMe file for details.
    
source "/data/SetupHelper/CommonResources"

#### end of lines to include SetupHelper

#### running manually and OK to proceed - prompt for input
if [ $scriptAction == 'NONE' ] ; then
    echo
    echo "The MultiTransferSwitch switches AC input parameters"
	echo "  between grid (shore) and generator"
	echo "Separte input source type and AC Input Current Limits are stored for each input"
	echo "A digital input tells this service which input is currently active"
	echo "The service then switches the AC 1 input between the two stored values"
    echo
    standardActionPrompt
fi

#### here to do the actual work

if [ $scriptAction == 'INSTALL' ] ; then
    logMessage "++ Installing ExtTransferSwitch"

    updateActiveFile "/opt/victronenergy/gui/qml/PageDigitalInput.qml"
    updateActiveFile "/opt/victronenergy/gui/qml/MbItemDigitalInput.qml"
    updateActiveFile "/opt/victronenergy/dbus-digitalinputs/dbus_digitalinputs.py"
    updateActiveFile "/opt/victronenergy/dbus-modbustcp/attributes.csv"

	# is GuiMods versions, do not replace
	file="/opt/victronenergy/dbus-generator-starter/startstop.py"
	if [ -f "$file" ] && (( $(grep -c "#### GuiMods" "$file") == 0 )); then
		updateActiveFile $file
		if $thisFileUpdated; then
			restartGeneratorService=true
		fi
		updateActiveFile "/opt/victronenergy/dbus-generator-starter/dbus_generator.py"
		if $thisFileUpdated; then
			restartGeneratorService=true
		fi
	fi

    installService $packageName

    if $filesUpdated ; then
        restartGui=true
    fi
fi

# #### uninstalling - check scriptAction again
# if an install step failed package needs to be removed
if [ $scriptAction == 'UNINSTALL' ] ; then
    logMessage "++ Uninstalling ExtTransferSwitch"

	# disable Ext Transfer Switch digital input
	# if not disabled dbus-digitalinputs will crash !!!
	digInputs=($(dbus -y | grep '.digitalinput.'))
	for digIn in ${digInputs[@]} ; do
		state=($(dbus -y $digIn /State GetValue ))
		if (( $state == 12 )) || (( $state == 13 )) ; then
			logMessage "disabling External Transfer Switch digital input $digIn"
			digInNumber=($(dbus -y $digIn /DeviceInstance GetValue ))
			dbus -y com.victronenergy.settings /Settings/DigitalInput/$digInNumber/Type SetValue 0 &> /dev/null
		fi
	done

	restoreActiveFile "/opt/victronenergy/gui/qml/PageDigitalInput.qml"
	restoreActiveFile "/opt/victronenergy/gui/qml/MbItemDigitalInput.qml"
	restoreActiveFile "/opt/victronenergy/dbus-digitalinputs/dbus_digitalinputs.py"
	restoreActiveFile "/opt/victronenergy/dbus-modbustcp/attributes.csv"

	# is GuiMods versions, do not uninstall
	file="/opt/victronenergy/dbus-generator-starter/startstop.py"
	if [ -f "$file" ] && (( $(grep -c "#### GuiMods" "$file") == 0 )); then
		restoreActiveFile $file
		if $thisFileUpdated; then
			restartGeneratorService=true
		fi
		restoreActiveFile "/opt/victronenergy/dbus-generator-starter/dbus_generator.py"
		if $thisFileUpdated; then
			restartGeneratorService=true
		fi
	fi

    removeService $packageName
fi

if $filesUpdated ; then
    restartGui=true
fi
if $restartGeneratorService ; then
    logMessage "restarting dbus-generator-starter service"
    svc -t /service/dbus-generator-starter
fi

logMessage "restarting dbus-digitalinputs service"
svc -t "/service/dbus-digitalinputs"

# thats all folks - SCRIPT EXITS INSIDE THE FUNCTION
endScript


